version: '3.4'
services: 
  redissi:
    image: "redis:alpine"
  backend: 
        build:  ./../../part1/1_11/backend-example-docker
        ports:
        - "8000:8000"
        environment:
        - REDIS=redissi
        - REDIS_PORT=6379
  frontend:
      build: ./../../part1/1_10/frontend-example-docker
      ports:
      - "5000:5000"
    